version: 2
jobs:
  build:
    working_directory: ~/stash_client
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run: yarn install
      - run: yarn build:development
        
  # deployment:
  #   release:
  #     tag: /release-.*/
  #     steps:
  #       - run:
  #           name: Build production
  #           command: yarn build:production
  #       - run:
  #           name: Copy production build to server
  #           command: scp -r dist/* $DO_USER@$DO_IP:/var/www/scroogevault.co/dist/
