version: 2
jobs:
  build-and-test:
    working_directory: ~/stash_client
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run:
          name: Step - Build
          command: |
            yarn install
            yarn build:production
      - run:
          name: Step - Lint
          command: yarn lint
      - run:
          name: Step - Test
          command: yarn test
  # deploy:
  #   steps:
  #     - run:
  #         name: Step - Lint
  #         command: yarn lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  build-test-and-deploy:
    jobs:
      - build-and-test
      # - deploy:
      #     requires:
      #       - build-and-test
        
  # deployment:
  #   release:
  #     tag: /release-.*/
  #     steps:
  #       - run:
  #           name: Step - Build Production
  #           command: yarn build:production
  #       - run:
  #           name: Step - Copy Production Build To Server
  #           command: scp -r dist/* $DO_USER@$DO_IP:/var/www/scroogevault.co/dist/
